### PR TITLE
Add Download PDF button

### PR DESCRIPTION
**Pull request by VladislavSokov**

### CODE REVIEW

**Comment by VladislavSokov** [comment]
[prevent-account-sharing.pdf](https://github.com/widefix/landing/files/15457553/prevent-account-sharing.pdf)
[stripe-integration.pdf](https://github.com/widefix/landing/files/15457556/stripe-integration.pdf)

**Comment by ka8725** [comment]
@VladislavSokov can we add margins to the left/right sides? I fee like it needs 10px.

**Comment by VladislavSokov** [comment]
[prevent-account-sharing.pdf](https://github.com/widefix/landing/files/15458090/prevent-account-sharing.pdf)
[stripe-integration.pdf](https://github.com/widefix/landing/files/15458092/stripe-integration.pdf)

**Comment by VladislavSokov** [comment]
[stripe-integration.pdf](https://github.com/widefix/landing/files/15473615/stripe-integration.pdf)
[prevent-account-sharing.pdf](https://github.com/widefix/landing/files/15473617/prevent-account-sharing.pdf)

**Comment by ka8725** [comment]
@VladislavSokov please use this PDF icon for the button: https://uxwing.com/download-pdf-icon/

Ax example of the position: 
image

**Comment by ka8725** [comment]
@VladislavSokov the quality of images in the resulting PDF is very pure. Moreover, their size is wrong - they are not full sized. Please fix.

**Comment by ka8725** [comment]
Current issues:

1. Fix the button position
2. The image does not fit into the image box in the PDF
3. no preview page to fix the issue 2
4. Improve original image quality and use the Next.js Image component facilities to generate variations, configure prerendered on CI

**Pull request merged**
